package diag

// FILE GENERATED BY gen/gen_errors.go; DO NOT EDIT!

// Type representing the error severity.
type Severity int

const (
	// Represents an error which must stop compilation.
	Error Severity = iota
	// Represents an error that doesn't need to stop compilation, but triggers a diagnostic.
	Warning
)

// A type for containing compilation errors.
type ErrorContainer struct {
	// The error code.
	Code string

	// The error message.
	Message string

	// The severity of the error.
	Severity Severity
}

type LexerErrorKind int

const (
	// Error message: Got an unexpected character
	LXUnexpectedChar LexerErrorKind = iota

	// Error message: String literal is not terminated
	LXUnterminatedString
)

var LexerErrorRegistry = map[LexerErrorKind]ErrorContainer{
	LXUnexpectedChar: {
		Code:     "LX0001",
		Message:  "Got an unexpected character",
		Severity: Error,
	},
	LXUnterminatedString: {
		Code:     "LX0002",
		Message:  "String literal is not terminated",
		Severity: Error,
	},
}

func (a LexerErrorKind) String() string {
	switch a {
	case LXUnexpectedChar:
		return "LXUnexpectedChar"
	case LXUnterminatedString:
		return "LXUnterminatedString"
	}
	return "[?]"
}
