// Code generated by "stringer -type TokenType ./internal/token"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokNone-0]
	_ = x[TokError-1]
	_ = x[TokEndOfFile-2]
	_ = x[TokI8-3]
	_ = x[TokI16-4]
	_ = x[TokI32-5]
	_ = x[TokI64-6]
	_ = x[TokU8-7]
	_ = x[TokU16-8]
	_ = x[TokU32-9]
	_ = x[TokU64-10]
	_ = x[TokF32-11]
	_ = x[TokF64-12]
	_ = x[TokChar-13]
	_ = x[TokString-14]
	_ = x[TokIdentifier-15]
	_ = x[TokOpPlus-16]
	_ = x[TokOpMinus-17]
	_ = x[TokOpStar-18]
	_ = x[TokOpSlash-19]
	_ = x[TokOpMod-20]
	_ = x[TokOpAssign-21]
	_ = x[TokOpEq-22]
	_ = x[TokOpNotEq-23]
	_ = x[TokOpLessThan-24]
	_ = x[TokOpGreaterThan-25]
	_ = x[TokOpLessEqual-26]
	_ = x[TokOpGreaterEqual-27]
	_ = x[TokOpenParen-28]
	_ = x[TokCloseParen-29]
	_ = x[TokOpenSquare-30]
	_ = x[TokCloseSquare-31]
	_ = x[TokOpenBracket-32]
	_ = x[TokCloseBracket-33]
	_ = x[TokOpDot-34]
	_ = x[TokOpColon-35]
	_ = x[TokOpDoubleColon-36]
	_ = x[TokOpComma-37]
	_ = x[TokSemicolon-38]
	_ = x[TokKwFunc-39]
	_ = x[TokKwReturn-40]
}

const _TokenType_name = "TokNoneTokErrorTokEndOfFileTokI8TokI16TokI32TokI64TokU8TokU16TokU32TokU64TokF32TokF64TokCharTokStringTokIdentifierTokOpPlusTokOpMinusTokOpStarTokOpSlashTokOpModTokOpAssignTokOpEqTokOpNotEqTokOpLessThanTokOpGreaterThanTokOpLessEqualTokOpGreaterEqualTokOpenParenTokCloseParenTokOpenSquareTokCloseSquareTokOpenBracketTokCloseBracketTokOpDotTokOpColonTokOpDoubleColonTokOpCommaTokSemicolonTokKwFuncTokKwReturn"

var _TokenType_index = [...]uint16{0, 7, 15, 27, 32, 38, 44, 50, 55, 61, 67, 73, 79, 85, 92, 101, 114, 123, 133, 142, 152, 160, 171, 178, 188, 201, 217, 231, 248, 260, 273, 286, 300, 314, 329, 337, 347, 363, 373, 385, 394, 405}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
